flat_first.qmd:
  path: dev/flat_first.qmd
  state: active
  R:
  - R/create-data-environment-on-load.R
  - R/read_parish_data.R
  - R/read_parish_table.R
  - R/good_ons_ids.R
  - R/good_levels.R
  - R/get_cpd_sheet.R
  - R/cpd_relative.R
  - R/read_cpd_stats.R
  tests:
  - tests/testthat/test-read_parish_data.R
  - tests/testthat/test-get_cpd_sheet.R
  - tests/testthat/test-cpd_relative.R
  - tests/testthat/test-read_cpd_stats.R
  vignettes: []
  inflate:
    flat_file: dev/flat_first.qmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
flat_get-deprivation-data-for-parishes.Rmd:
  path: dev/flat_get-deprivation-data-for-parishes.Rmd
  state: active
  R:
  - R/coe_parish_deprivation.R
  - R/get-deprivation-data-with-coe_parish_deprivation--or-coe_parish_imd-.R
  tests: tests/testthat/test-coe_parish_deprivation.R
  vignettes: vignettes/parish-deprivation-data.Rmd
  inflate:
    flat_file: dev/flat_get-deprivation-data-for-parishes.Rmd
    vignette_name: Parish-level Deprivation data
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
flat_read_church_data.Rmd:
  path: dev/flat_read_church_data.Rmd
  state: active
  R:
  - R/coe_churches.R
  - R/coe_esri_fields.R
  - R/coe_parish_from_church.R
  tests: tests/testthat/test-coe_churches.R
  vignettes: vignettes/individual-church-data.Rmd
  inflate:
    flat_file: dev/flat_read_church_data.Rmd
    vignette_name: Data on individual churches
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
flat_reading-coe-statistics.Rmd:
  path: dev/flat_reading-coe-statistics.Rmd
  state: active
  R:
  - R/coe_census.R
  - R/coe_census_datasets.R
  - R/coe_census_diocese.R
  - R/coe_census_england.R
  - R/coe_census_parish.R
  - R/coe_parish_snapshot.R
  tests:
  - tests/testthat/test-coe_census.R
  - tests/testthat/test-coe_parish_snapshot.R
  vignettes: vignettes/coe-census-data.Rmd
  inflate:
    flat_file: dev/flat_reading-coe-statistics.Rmd
    vignette_name: CoE census statistics
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
keep:
  path: keep
  R:
  - R/aaa.R
  - R/dplyr_subclass_methods.R
