---
title: "flat_read_church_data.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

## coe_church_data

Get tidy data on Church of England churches. 

```{r function-coe_church_data}
#' Get church-level data from CoE data services
#'
#' Reads church data from the Church of England's [Data Services ESRI feature server](https://services5.arcgis.com/KDRjxGRQDVgVtFTS/ArcGIS/rest/services/Churches_ACNY_Nov2024/FeatureServer), dropping spatial data and returning a [tibble::tibble()].
#'
#' @param where An SQL query. The default returns all churches. See details.
#' @return A tibble in which each row corresponds to a church in the Church of England
#'
#' @details
#' This function renames fields in the returned tibble, but any query passed to `where` must use the original names of the ESRI data provided by CoE data services. The names of these fields
#' can be accessed via [coe_esri_fields()]
#' 
#' 
#' @export
#'
#'
#' @examples
coe_church_data <- function(where = "1=1") {

req <-
  httr2::request("https://services5.arcgis.com") |> 
  httr2::req_url_path("KDRjxGRQDVgVtFTS/arcgis/rest/services/Churches_ACNY_Nov2024/FeatureServer/0/query") |> 
  httr2::req_url_query(where = where, outFields = "*", returnGeometry = "false", f = "geojson")

churches <- sf::st_read(req$url, quiet = TRUE)

churches <- tibble::as_tibble(churches)

churches <- churches[c("ChurchCode", "ParLocNa", "ParishID", "BenefNa", "BenefID",
                       "DeanNa", "DeanID", "ArchdNa", "ArchdID", "DioNa", "DioID")]

names(churches) <- c("church_code", "parish_name", "parish_code", "benefice_name", "benefice_id",
                     "deanery_name", "deanery_id", "archdeaconry_name", "archdeaconry_id", "diocese_name", "diocese_number")

churches
}
```

```{r examples-coe_church_data}
coe_church_data(where = "ChurchCode = 608186") |>
  dplyr::glimpse()
```

```{r tests-read_church_data}
test_that("read_church_data works", {
  expect_true(inherits(coe_church_data, "function"))
})
```

## coe_esri_fields

This tiny function returns the names of the fields used in the Feature Server of Churches provided by CoE Data Services through ESRI.

```{r function-coe_esri_fields}
#' View fields that can be passed to the `where` argument of [coe_church_data]

#' @returns A character vector of field names
#' @export
coe_esri_fields <- function(){
  c("FID", "ChurchCode", "ChurchName", "ACNY_url", "ACNY_id", "Heritg_url",
    "LBGrade", "ParLocNa", "ParLegNa", "ParishID", "BenefNa", "BenefID", 
    "DeanNa", "DeanID", "ArchdNa", "ArchdID", "DioNa", "DioID")
}
```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_read_church_data.Rmd", vignette_name = "Go further")
```

