---
title: "flat_first.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# parish_stats
    
```{r function-parish_stats}
#' Get census data for CoE parishes
#' 
#' Get 2021 ONS census data for any number of Church of England parishes
#' 
#' @return A single tibble
#' @param nomis_code The nomis code for the data required must be a length-one character.
#' @param parish_codes Character vector of parishes for which data are desired. If `NULL` (the default), all parishes are returned
#' @param relative Logical. Should a tibble of relative values be returned? The default is absolute values.
#' 
#' @export
parish_stats <- function(nomis_code, parish_codes = NULL, relative = FALSE){
  
  if(length(nomis_code) != 1 || !is.character(nomis_code)) rlang::abort("nomis_codes must be a character vector with length one")
  if(!is.null(parish_codes) && !is.character(parish_codes))rlang::abort("parish_codes must be a character vector with length one")

  par <-
    if(relative) ps_coe_parishes_rel
  else ps_coe_parishes
  
  if(!nomis_code %in% par$nomis_code){
    rlang::abort(paste0("nomis_code '", nomis_code, "' represents a data set that does not exist or is not available"))
  }
  
  par <- par[par$nomis_code %in% nomis_code, ][["data"]][[1]]
  if(!is.null(parish_codes)) par <- par[par$parish_code %in% parish_codes,]
  
  par
}
```
  
```{r example-parish_stats}
parish_stats("TS001") |> 
  head()

parish_stats("TS004", c("100001", "100006"))
```
  
```{r tests-parish_stats}
test_that("parish_stats works", {
  expect_true(inherits(parish_stats, "function")) 
})

test_that("parish_stats fails properly",{
  ## Missing arguments
  expect_error(parish_stats())
  ## More than one nomis_code
  expect_error(parish_stats(c("TS004", "TS001")))
  ## nomis_code not in list
  expect_error(parish_stats("bad-nomis-code"))
})

test_that("parish_stats works with no parish codes", {
  expect_no_condition(parish_stats("TS004"))
})
```

## map_parish_stats

```{r function-map-parish-stats}
#' Get a list of tibble containing parish-level UK census data
#' 
#' This function is a wrapper around [parish_stats()] that returns a list of tibbles
#' 
#' @return A list of tibbles
#' @param nomis_codes The nomis code for the data required must be a length-one character.
#' @param parish_codes Character vector of parishes for which data are desired. If `NULL` (the default), all parishes are returned
#' @param relative Logical. Should a tibble of relative values be returned? The default is absolute values.
#' 
#' @export

map_parish_stats <- function(nomis_codes, ...){
  lapply(nomis_codes, \(x) parish_stats(x, ...))
}
```

```{r examples-map-parish-stats}
map_parish_stats(c("TS004", "TS001"))
map_parish_stats(c("TS004", "TS001"), parish_codes = "100006")
```

```{r tests-map-parish-stats}
test_that("map-parish-stats works", {
  inherits(map_parish_stats, "function")
  expect_no_condition(map_parish_stats(c("TS004", "TS001")))
})

test_that("map-parish-stats crashes",{
  expect_error(map_parish_stats(c("TS004", "bad-nomis-code")))
})
```
