# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

test_that("map-parish-stats works", {
  inherits(map_parish_stats, "function")
  expect_no_condition(map_parish_stats(c("TS004", "TS001")))
})

test_that("map-parish-stats crashes",{
  expect_error(map_parish_stats(c("TS004", "bad-nomis-code")))
})
