# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

test_that("cpd_relative() works",{
  expect_true(inherits(cpd_relative, "function"))
  expect_no_error(cpd_relative(read_cpd_stats("TS001", "diocese")))
})
