# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

test_that("read_cpd_stats works",{
  expect_true(inherits(read_cpd_stats, "function"))
  
  expect_no_error(read_cpd_stats("TS001", "diocese"))
  expect_s3_class(read_cpd_stats("TS001", "diocese"), c("coe_parish_data", "tbl_df"))
})

test_that("caching is working for parish data",{
  ## Read the data
  read_cpd_stats("TS001", "parish")

  ## Check it has cached
  tmp_dat <-  read_parish_data()
  cached <- tmp_dat$data[tmp_dat$level == "parish" & tmp_dat$nomis_code == "TS001"][[1]]

  expect_s3_class(cached, c("coe_parish_data", "tbl_df"))
   })

test_that("class information is not duplicated", {
  expect_true(all(table(class(read_cpd_stats("TS001", "diocese"))) == 1))
})
