# WARNING - Generated by {fusen} from dev/flat_reading-coe-statistics.Rmd: do not edit by hand

test_that("coe_parish_snapshot works", {
  expect_true(inherits(coe_parish_snapshot, "function"))
  
  test <- coe_parish_snapshot("370047", ons_ids = "TS001")
  
  expect_type(test, "list")
  
  expect_equal(nrow(test[[1]]), 3)
})
