# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

test_that("get_cpd_sheet works",{
  expect_true(inherits(get_cpd_sheet, "function"))
  
  will_work <- min(which(!is.na(read_parish_data()$drive_id)))

  drived <- read_parish_data()$drive_id[will_work]
  sheet  <- read_parish_data()$ons_id[will_work]

  expect_no_error(get_cpd_sheet(drived, sheet))
  })
