# WARNING - Generated by {fusen} from dev/flat_read_church_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("coe_churches works", {
  expect_true(inherits(coe_churches, "function"))
})
