# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

test_that("parish_stats works", {
  expect_true(inherits(parish_stats, "function")) 
})

test_that("parish_stats fails properly",{
  ## Missing arguments
  expect_error(parish_stats())
  ## More than one nomis_code
  expect_error(parish_stats(c("TS004", "TS001")))
  ## nomis_code not in list
  expect_error(parish_stats("bad-nomis-code"))
})

test_that("parish_stats works with no parish codes", {
  expect_no_condition(parish_stats("TS004"))
})
