# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

test_that("read_parish_data works", {
  expect(inherits(read_parish_data, "function"), "read_parish_data is not a function")
  expect_s3_class(read_parish_data(), "tbl_df")
})
