# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

test_that("get_anglican_stats works",{
  expect_true(inherits(read_cpd_stats, "function"))
  
  expect_no_error(read_cpd_stats("TS001", "diocese"))
  expect_s3_class(read_cpd_stats("TS001", "diocese"), c("coe_parish_data", "tbl_df"))
})

test_that("caching is working for parish data",{
  ## Check there's nothing there

  tmp_dat <- read_parish_data()
  
  expect_identical(tmp_dat$data[tmp_dat$level == "parish" & tmp_dat$nomis_code == "TS001"],
                   list(NULL))
  
  ## Read the data
  read_cpd_stats("TS001", "parish")

  ## Check it has cached
  tmp_dat <- read_parish_data()
  cached <- tmp_dat$data[tmp_dat$level == "parish" & tmp_dat$nomis_code == "TS001"][[1]]
  
  expect_true(!is.null(cached))
  expect_s3_class(cached, c("coe_parish_data", "tbl_df"))
   })
