# WARNING - Generated by {fusen} from dev/flat_reading-coe-statistics.Rmd: do not edit by hand

test_that("coe_stats works", {
  expect_true(inherits(coe_stats, "function"))
  expect_s3_class(
    coe_stats("TS004", "parish"),
    c("coe_parish_data", "tbl_df")
  )
})

test_that("coe_stats doesn't work when it shouldn't", {
  
  expect_error(coe_stats("TS001", level = c("parish", "diocese")),
               class = "coe_bad_level",
               regexp = "length")
  
  expect_error(coe_stats("TS001", level = "bad_value"),
               class = "coe_bad_level")
  
  expect_error(coe_stats(c("TS001", "TS002")),
               class = "coe_bad_nomis_code",
               regexp = "length")
  
  expect_error(coe_stats("bad_nomis_code"),
               class = "coe_bad_nomis_code")
  
  expect_warning(coe_stats("TS001", level = "parish", areas = NA_character_),
                 class = "coe_warn_areas")
  
  expect_error(coe_stats("TS001", level = "england", areas = "yes"),
               class = "coe_areas_with_england")
})
