# WARNING - Generated by {fusen} from dev/flat_reading-coe-statistics.Rmd: do not edit by hand

test_that("coe_parish_census_context works", {
  expect_true(inherits(coe_parish_census_context, "function"))
  
  test <- coe_parish_census_context("370047", nomis_codes = "TS001")
  
  expect_type(test, "list")
  
  expect_equal(nrow(test[[1]]), 3)
})
