# WARNING - Generated by {fusen} from dev/flat_reading-coe-statistics.Rmd: do not edit by hand

#' Obtain national level statistics on a particular topic
#' 
#' @param ons_id The ONS id for the required topic
#' @param ... Other arguments passed to [coe_census_stats()]
#' 
#' @export
coe_england_census_stats <- function(ons_id, ...){
  coe_census_stats(ons_id, level = "england", ...)
}
