# WARNING - Generated by {fusen} from dev/flat_read_church_data.Rmd: do not edit by hand

#' Get the parish codes of any number of Church of England churches.
#' 
#' @param church_codes A character vector of church codes
#' @return A character vector of parish codes, with the same length as `church_codes`
#' 
#' @export
#' @examples
#' coe_parish_from_church(c(635041, 623001))

coe_parish_from_church <- function(church_codes){
  
  query_codes <- paste0("(", paste(church_codes, collapse = ", "), ")")
  
  query <- paste("ChurchCode IN", query_codes)
  
  parishes <- esri_churches(where = query, outFields = "ChurchCode, ParishID")
  
  parishes$ParishID[match(church_codes, parishes$ChurchCode)]
}
