# WARNING - Generated by {fusen} from dev/flat_reading-coe-statistics.Rmd: do not edit by hand

#' Get Census data for the Church of England at a parish, diocesan or national level.
#'
#' @return A  
#' @param nomis_code The Nomis code of required data. Must be one of [coe_datasets()].
#' @param level The geographical level at which data are required. Must be one of 'parish', 'diocese' or 'england'.
#' @param areas A character vector of parish codes or diocese numbers. If specified, the returned tibble will contain only data for these areas. Cannot be used with `level = 'england'`. `NA` values will be removed.
#' @param relative Logical. Should returned table contain absolute statitiscs (e.g. persons/households) or proportions for each area?
#' @export
#'
#' @examples
#' coe_stats(nomis_code =  "TS001", level = "england")
#' coe_stats(nomis_code = "TS001", level = "diocese", areas = 1)
coe_stats <- function(nomis_code, level, areas, relative = FALSE){
  
  ## Validate inputs
  
  ### Check nomis_code is character vector with length one
  if(!is.character(nomis_code) || length(nomis_code) != 1) rlang::abort("Argument nomis_code must be a character vector with length 1", class = "coe_bad_nomis_code")
  
  ### Check nomis_code's are all good
  if(!all(nomis_code %in% good_nomis_codes())){
    
    rlang::abort(c("Argument nomis_code pertains to data that is not available through this package:", nomis_code),
                 class = "coe_bad_nomis_code")
  }
  
  ### level must be length 1
  if(length(level) != 1 || !is.character(level)) rlang::abort("Argument 'level' must be a character vector with length 1.",
                                                              class = "coe_bad_level")
  
  ### Check level are all good
  if(!all(level %in% good_levels())){
    good_level_txt <-
      as.character(good_levels()) |> 
      paste0("\"", foo = _, "\"")
    
    good_level_text <- paste0("c(", paste(good_level_txt, collapse = ", "), ")") 
    
    rlang::abort(c(
      paste("Argument 'level' must be one of: ", good_level_text),
      `!` = "Problematic argument:",
      `x` = paste0("level = ", level)),
      class = "coe_bad_level")
  }
  
  ## Validate areas
  ### No missing values
  if(!rlang::is_missing(areas) && any(is.na(areas))){
    rlang::warn("Ignoring missing values in argument 'areas'", class = "coe_warn_areas")
    areas <- areas[!is.na(areas)]
  }
  
  ## Get data
  out <- read_cpd_stats(nomis_code, level)

  if(!rlang::is_missing(areas)){
    if(level == "parish")  out <- out[out$parish_code %in% areas, ]
    if(level == "diocese") out <- out[out$diocese_number %in% areas, ]
    if(level == "england") rlang::abort("Argument 'areas' provided but can not be used with level = 'england'",
                                        class = "coe_areas_with_england")
  }
  
  if(relative) out <- cpd_relative(out)
  
  out
}
