# WARNING - Generated by {fusen} from dev/flat_read_church_data.Rmd: do not edit by hand

#' Get parish code(s) from church code(s)
#' 
#' @param church_codes A character vector of church codes
#' @return A character vector of parish codes, with the same length as `church_codes`
#' 
#' @export

coe_church_parish <- function(church_codes){
  
  query_codes <- paste0("(", paste(church_codes, collapse = ", "), ")")
  
  query <- paste("ChurchCode IN", query_codes)
  
  parishes <- esri_churches(where = query, outFields = "ChurchCode, ParishID")
  
  parishes$ParishID[match(church_codes, parishes$ChurchCode)]
}
