# WARNING - Generated by {fusen} from dev/flat_reading-coe-statistics.Rmd: do not edit by hand

#' @noRd
# TODO: Add data/function for reading 'parish map'
coe_parish_in_context <- function(parish_code, nomis_codes = coe_nomis_codes(description = FALSE)){
  
  p_table <- read_parish_table()
  
  nomis_codes = as.list(nomis_codes)
  names(nomis_codes) = nomis_codes
  
  if(length(parish_code) != 1 || !is.character(parish_code)) rlang::abort("Argument 'parish_code' must be a character vector of length one")
  if(!parish_code %in% p_table$parish_code) rlang::abort(c("Parish code:", x = parish_code, "is not valid"))
  
  diocese_no <- p_table$diocese_number[p_table$parish_code == parish_code]
  
  parish_stats  <- lapply(nomis_codes, \(x) coe_stats(nomis_code = x, level = "parish",  areas = parish_code))
  diocese_stats <- lapply(nomis_codes, \(x) coe_stats(nomis_code = x, level = "diocese", areas = diocese_no))
  england_stats <- lapply(nomis_codes, \(x) coe_stats(nomis_code = x, level = "england"))
  
  
  out <- vector("list", length(nomis_codes))
  
  for(code in nomis_codes){
    out[code] <- rbind(parish_stats[code], diocese_stats[code], england_stats[code])
  }
  
  out
}

