# WARNING - Generated by {fusen} from dev/flat_reading-coe-statistics.Rmd: do not edit by hand

#' Get a (list of) comparative table(s) of local, diocesan and national data for a given parish
#' 
#' Extracts parish, diocese and national level data for a given parish, then [base::rbind]s them into a single table. Iterates over `ons_ids` to output a list of such tables
#' @returns A list of `coe_parish_data` tibbles
#' @param parish_code A single parish code. Character.
#' @param ons_ids A character vector of ons_ids.
#' @param relative Logical. Should outputs be relative? Default is `TRUE`.
#' @export
#' @examples
#' coe_parish_census_context(parish_code = "370047", ons_ids = "TS001")

coe_parish_census_context <- function(parish_code,
                                  ons_ids = coe_datasets(description = FALSE),
                                  relative = TRUE){
  
  p_table <- read_parish_table()
  
  ons_ids = as.list(ons_ids)
  names(ons_ids) = ons_ids
  
  if(length(parish_code) != 1 || !is.character(parish_code)) rlang::abort("Argument 'parish_code' must be a character vector of length one")
  if(!parish_code %in% p_table$parish_code) rlang::abort(c("Parish code:", x = parish_code, "is not valid"))
  
  diocese_no <- p_table$diocese_number[p_table$parish_code == parish_code]
  
  par_table <- read_parish_table()
  par_table <- par_table[par_table$parish_code %in% parish_code,]
  
  parish_stats  <- lapply(ons_ids,
                          \(x){
                            stat_table <- coe_census(ons_id = x, level = "parish",  areas = parish_code, relative = relative) 
                            
                            stat_table$parish_name <- par_table$parish_name[match(stat_table$parish_code, par_table$parish_code)]
                            
                            stat_table <- coe_relocate(stat_table, c("parish_code", "parish_name"))
                            names(stat_table)[1:2] <- c("level_code", "level_name")
                            stat_table$level <- "parish"
                            stat_table <- coe_relocate(stat_table, "level")
                            stat_table
                            
                            })
  
  diocese_stats <- lapply(ons_ids,
                          \(x){
                            stat_table <- coe_census(ons_id = x, level = "diocese", areas = diocese_no, relative = relative)
                            
                            stat_table$diocese_name <- par_table$diocese_name[match(stat_table$diocese_number, par_table$diocese_number)]
                            
                            stat_table <- coe_relocate(stat_table, c("diocese_number", "diocese_name"))
                            names(stat_table)[1:2] <- c("level_code", "level_name")
                            stat_table$level <- "diocese"
                            stat_table <- coe_relocate(stat_table, "level")
                            stat_table
                            
                            })
  england_stats <- lapply(ons_ids,
                          \(x){
                            stat_table <- coe_census(ons_id = x, level = "england", relative = relative)
                            
                            stat_table$level <- "nation"
                            stat_table$level_code = NA_character_
                            stat_table$level_name = "england"
                            
                            stat_table <- coe_relocate(stat_table, c("level", "level_code", "level_name"))
                            stat_table
                            
                            })
  
  
  out <- vector("list", length(ons_ids))
  names(out) <-  names(ons_ids)
  
  for(code in names(ons_ids)){
    out[[code]] <- rbind(parish_stats[[code]], diocese_stats[[code]], england_stats[[code]])
  }
  
  out
}


#' @noRd
coe_relocate <- function(.data, cols){
  out <- .data[,c(cols, setdiff(names(.data), cols))]
  out
}
