# WARNING - Generated by {fusen} from dev/flat_read_church_data.Rmd: do not edit by hand

#' View fields that can be passed to the `where` argument of [coe_churches()]

#' @returns A character vector of field names
#' @export
coe_esri_fields <- function(){
  c("FID", "ChurchCode", "ChurchName", "ACNY_url", "ACNY_id", "Heritg_url",
    "LBGrade", "ParLocNa", "ParLegNa", "ParishID", "BenefNa", "BenefID", 
    "DeanNa", "DeanID", "ArchdNa", "ArchdID", "DioNa", "DioID")
}
