# WARNING - Generated by {fusen} from dev/flat_reading-coe-statistics.Rmd: do not edit by hand

#' Obtain dicoese level statistics on a particular topic for any diocese of your choosing
#' 
#' @param ons_id The ONS id the required topic
#' @param parish_codes Parish codes of required parishes. If empty (the default) data for all parishes are returned.
#' @param ... Other arguments passed to [coe_census_stats()]
#' 
#' @export 
coe_parish_census_stats <- function(ons_id, parish_codes, ...){
  
  if(!rlang::is_missing(parish_codes)) out <- coe_census_stats(ons_id, level = "parish", areas = parish_codes, ...)
  else out <- coe_census_stats(ons_id, level = "parish", ...)
  out
}
