# WARNING - Generated by {fusen} from dev/flat_read_church_data.Rmd: do not edit by hand

#' Get data on the Anglican geography on Church of England Churches, including their parish, benefice, arcdeaconry and diocese. 
#'
#' Reads church data from the Church of England's [Data Services ESRI feature server](https://services5.arcgis.com/KDRjxGRQDVgVtFTS/ArcGIS/rest/services/Churches_ACNY_Nov2024/FeatureServer), dropping spatial data and returning a [tibble::tibble()].
#'
#' @param where An SQL query. The default returns all churches. See details.
#' @return A tibble in which each row corresponds to a church in the Church of England
#'
#' @details
#' This function renames fields in the returned tibble, but any query passed to `where` must use the original names of the ESRI data provided by CoE data services. The names of these fields
#' can be accessed via [coe_esri_fields()]
#' 
#' @export
#' @examples
#' coe_churches(where = "ChurchCode = 608186") |>
#'   dplyr::glimpse()
coe_churches <- function(where = "1=1") {

churches <- esri_churches(where = where, outFields = "*")

churches <- churches[c("ChurchCode", "ParLocNa", "ParishID", "BenefNa", "BenefID",
                       "DeanNa", "DeanID", "ArchdNa", "ArchdID", "DioNa", "DioID")]

names(churches) <- c("church_code", "parish_name", "parish_code", "benefice_name", "benefice_id",
                     "deanery_name", "deanery_id", "archdeaconry_name", "archdeaconry_id", "diocese_name", "diocese_number")

churches
}

#' @noRd
esri_churches <- function(where, outFields){
  req <-
  httr2::request("https://services5.arcgis.com") |> 
  httr2::req_url_path("KDRjxGRQDVgVtFTS/arcgis/rest/services/Churches_ACNY_Nov2024/FeatureServer/0/query") |> 
  httr2::req_url_query(where = where, outFields = outFields, returnGeometry = "false", f = "geojson")

  churches <- sf::st_read(req$url, quiet = TRUE)

  churches <- tibble::as_tibble(churches)
  churches <- churches[!names(churches) %in% c("geometry", "lattitude", "longitude")]
  churches
}
