# WARNING - Generated by {fusen} from dev/flat_reading-coe-statistics.Rmd: do not edit by hand

#' Obtain national level census statistics on a given topic
#' 
#' @param ons_id The ONS id for the required topic
#' @param ... Other arguments passed to [coe_census()]
#' 
#' @export
coe_census_england <- function(ons_id, ...){
  coe_census(ons_id, level = "england", ...)
}
