# WARNING - Generated by {fusen} from dev/flat_reading-coe-statistics.Rmd: do not edit by hand

#' Obtain national level statistics on a particular topic
#' 
#' @param nomis_code The nomis code for the required topic
#' @param ... Other arguments passed to [coe_stats()]
#' 
#' @export
coe_england_stats <- function(nomis_code, ...){
  coe_stats(nomis_code, level = "england", ...)
}
