# WARNING - Generated by {fusen} from dev/flat_reading-coe-statistics.Rmd: do not edit by hand

#' Obtain diocese-level census statistics on a given topic
#' 
#' @param ons_id The ONS id for the required topic
#' @param diocese_numbers Diocese numbers of required dioceses. If empty (the default) data for all dioceses are returned.
#' @param ... Other arguments passed to [coe_census()]
#' 
#' @export
#' @examples
#' coe_census_diocese(ons_id = "TS062", diocese_numbers = c(3, 7), relative = TRUE)
coe_census_diocese <- function(ons_id, diocese_numbers, ...){
  
  if(!rlang::is_missing(diocese_numbers)) out <- coe_census(ons_id, level = "diocese", areas = diocese_numbers, ...)
  else out <- coe_census(ons_id, level = "diocese", ...)
  out
}
