# WARNING - Generated by {fusen} from dev/flat_read_church_data.Rmd: do not edit by hand # nolint: line_length_linter.

#' View fields that can be passed to the `where` argument of [coe_churches()]

#' @returns A character vector of field names
#' @export
#' @examples
#' coe_esri_fields()
coe_esri_fields <- function(){
  c("FID", "Church_Cod", "ChurchName", "ACNY_id", "ACNY_url", "Church_Her",
    "LBGrade", "ParLocNa", "ParLegNa", "ParishID", "BenefNa", "BenefID", 
    "DeanNa", "DeanID", "ArchdNa", "ArchdID", "DioNa", "DioID")
}
