# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

#' @noRd
cpd_relative <- function(.data){
  if(!"coe_parish_data" %in% class(.data)) rlang::abort("'.data' must be a coe_parish_data object.")
  
  units <- attr(.data, "units")
  
  if(units == "persons")                   col <- "population"
  else if(units == "persons_sixteen_plus") col <- "population_16_and_over"
  else if(units == "households")           col <- "occupied_households"
  else rlang::abort("'units' attribute of '.data' not recognised")
  
  ignore <- c("parish_code", "parish_name", "diocese_number", "diocese_name")
  
  names_list <- names(.data)[!names(.data) %in% c(col, ignore)]
  
  for(col_name in names_list){
    .data[[col_name]] <- .data[[col_name]] / .data[[col]]
  }
  
  attr(.data, "relative") <- TRUE
  attr(.data, "units") <- c("Proportion of all ", attr(.data, "units"))
  .data
  
}
