# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

rlang::on_load({
  .coeparishdata_envir <- new.env(parent = emptyenv())
  .coeparishdata_envir$parish_data <- tibble::as_tibble(parish_data)
  .coeparishdata_envir$parishes_2024 <- NULL
  })
