# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

rlang::on_load({
  .coeparishdata_envir <- new.env(parent = emptyenv())
  # utils::data("sysdata", package = "coeparishdata", envir = .coeparishdata_envir)
  .coeparishdata_envir$parish_data <- parish_data
  })
