# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

rlang::on_load({
  .coedata_envir <- new.env(parent = emptyenv())
  .coedata_envir$parish_data <- tibble::as_tibble(parish_data)
  .coedata_envir$parishes_2024 <- NULL
  .coedata_envir$parish_imd_2019 <- NULL
  })
