# WARNING - Generated by {fusen} from dev/flat_get-deprivation-data-for-parishes.Rmd: do not edit by hand # nolint: line_length_linter.


#' @rdname coe_parish_deprivation
#' @export
coe_parish_imd <- coe_parish_deprivation

