# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

#' @noRd
get_cpd_sheet <- function(drive_id, sheet){
  
  googlesheets4::gs4_deauth()
  
  googlesheets4::read_sheet(ss = drive_id, sheet = sheet)
}
