# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

#' Get a list of tibble containing parish-level UK census data
#' 
#' This function is a wrapper around [parish_stats()] that returns a list of tibbles
#' 
#' @return A list of tibbles
#' @param nomis_codes The nomis code for the data required must be a length-one character.
#' @param ... Arguments passed to [parish_stats()]
#' 
#' @export
#' @examples
#' map_parish_stats(c("TS004", "TS001"))
#' map_parish_stats(c("TS004", "TS001"), parish_codes = "100006")

map_parish_stats <- function(nomis_codes, ...){
  lapply(nomis_codes, \(x) parish_stats(x, ...))
}
