# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

#' Get census data for CoE parishes
#' 
#' Get 2021 ONS census data for any number of Church of England parishes
#' 
#' @return A single tibble
#' @param nomis_code The nomis code for the data required must be a length-one character.
#' @param parish_codes Character vector of parishes for which data are desired. If `NULL` (the default), all parishes are returned
#' @param relative Logical. Should a tibble of relative values be returned? The default is absolute values.
#' 
#' @export
#' @examples
#' parish_stats("TS001") |> 
#'   head()
#'
#' parish_stats("TS004", c("100001", "100006"))
parish_stats <- function(nomis_code, parish_codes = NULL, relative = FALSE){
  
  if(length(nomis_code) != 1 || !is.character(nomis_code)) rlang::abort("nomis_codes must be a character vector with length one")
  if(!is.null(parish_codes) && !is.character(parish_codes))rlang::abort("parish_codes must be a character vector with length one")

  par <-
    if(relative) ps_coe_parishes_rel
  else ps_coe_parishes
  
  if(!nomis_code %in% par$nomis_code){
    rlang::abort(paste0("nomis_code '", nomis_code, "' represents a data set that does not exist or is not available"))
  }
  
  par <- par[par$nomis_code %in% nomis_code, ][["data"]][[1]]
  if(!is.null(parish_codes)) par <- par[par$parish_code %in% parish_codes,]
  
  par
}
