# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

#' Low level function for getting parish-level census data
#' 
#' Get 2021 ONS census data for any number of parishes, dioceses or the whole of England. Parish data is read from a Google sheet
#' 
#' @return A single tibble
#' @param nomis_code Nomis code of required data set
#' @param level One of 'parish', 'diocese' or 'england'
#' 
#' @noRd
read_cpd_stats <- function(nomis_code, level){
  
  cpd_pd <- read_parish_data()

  requested_row <- which(cpd_pd$nomis_code == nomis_code & cpd_pd$level == level)
  stopifnot(length(requested_row) == 1)
  
  local_data <- cpd_pd$local[requested_row]
  
  if(local_data){
    out <- cpd_pd$data[requested_row][[1]]
  } else{
    # Read google sheet
    out <- get_cpd_sheet(cpd_pd$drive_id[requested_row], cpd_pd$nomis_code[requested_row])
    ## Assign class and units attributes
    class(out)            <- c("coe_parish_data", class(out))
    attr(out, "nomis_code") <- cpd_pd$nomis_code[requested_row]
    attr(out, "description") <- cpd_pd$description[requested_row]
    attr(out, "units")    <- cpd_pd$units[requested_row]
    attr(out, "relative") <- FALSE
    
    ## Update data environment with sheet read from google
    .coeparishdata_envir$parish_data[["data"]][[requested_row]] <- out
    .coeparishdata_envir$parish_data[requested_row, "local"] <- TRUE
  }
  out
}
