# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

#' @noRd
read_parish_table <- function(){
  p_table <- .coeparishdata_envir$parishes_2024
  
  if(is.null(p_table)){
    p_table <- coe_churches()
    
    p_table <-
      p_table[-which(names(p_table) == "church_code")] |> 
      unique()

    .coeparishdata_envir$parishes_2024 <- p_table
  } 
  
  p_table
}
