# WARNING - Generated by {fusen} from dev/flat_first.qmd: do not edit by hand

#' @noRd
read_parish_table <- function(){
  p_table <- .coeparishdata_envir$parishes_2024
  
  if(is.null(p_table)){
    p_table <- get_cpd_sheet("1UUUU96Iw5i0JmabEIczmi6DrDsPIw6yfsGwSO5ExeT0", "parishes")
    .coeparishdata_envir$parishes_2024 <- p_table
  } 
  
  p_table
}
